CREATE TABLE IF NOT EXISTS USUARIO_CATEGORIA (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(25),
    DATA_INCLUSAO DATE DEFAULT NOW(),
    USUARIO_INCLUSAO VARCHAR(255),
    DATA_ALTERACAO DATE,
    USUARIO_ALTERACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID INTEGER PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(255),
    SENHA VARCHAR(255),
    CATEGORIA_ID INTEGER CONSTRAINT FK_USUARIO_CATEGORIA REFERENCES USUARIO_CATEGORIA(ID),
    DATA_INCLUSAO DATE DEFAULT NOW(),
    USUARIO_INCLUSAO VARCHAR(255),
    DATA_ALTERACAO DATE,
    USUARIO_ALTERACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS POSTAGEM (
    ID INTEGER PRIMARY KEY,
    TITULO VARCHAR(255),
    DESCRICAO TEXT,
    USUARIO_ID INTEGER CONSTRAINT FK_USUARIO REFERENCES USUARIO(ID),
    DATA_INCLUSAO DATE DEFAULT NOW(),
    USUARIO_INCLUSAO VARCHAR(255),
    DATA_ALTERACAO DATE,
    USUARIO_ALTERACAO VARCHAR(255)
);

CREATE SEQUENCE USUARIO_CATEGORIA_SEQ_ID;
CREATE SEQUENCE USUARIO_SEQ_ID;
CREATE SEQUENCE POSTAGEM_SEQ_ID;

INSERT INTO USUARIO_CATEGORIA(ID, NOME, USUARIO_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Aluno', 'Sistema');
INSERT INTO USUARIO_CATEGORIA(ID, NOME, USUARIO_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Professor', 'Sistema');
INSERT INTO USUARIO_CATEGORIA(ID, NOME, USUARIO_INCLUSAO) VALUES (NEXTVAL('USUARIO_CATEGORIA_SEQ_ID'), 'Administrador', 'Sistema');
